### ISSUE TITLE
Kind/Question Is this the normal behaviour?

### ISSUE THREAD

**Issue by cescoferraro** [webpack-contrib/raw-loader#13]
### Code
```
let text = require("./text.txt");
let svg = require("./ic_list_black_48px.svg");
console.log(text);
console.log(svg);
```
### test.txt & ic_list_black_48px.svg are completly the same

```
<svg fill="#000000" height="48" viewBox="0 0 24 24" width="48" xmlns="http://www.w3.org/2000/svg">
    <path d="M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7z"/>
    <path d="M0 0h24v24H0z" fill="none"/>
</svg>
```

### Console
```
playlist.tsx?1942:15
<svg fill="#000000" height="48" viewBox="0 0 24 24" width="48" xmlns="http://www.w3.org/2000/svg">
    <path d="M3 13h2v-2H3v2zm0 4h2v-2H3v2zm0-8h2V7H3v2zm4 4h14v-2H7v2zm0 4h14v-2H7v2zM7 7v2h14V7H7z"/>
    <path d="M0 0h24v24H0z" fill="none"/>
</svg>

playlist.tsx?1942:16
module.exports = "data:image/svg+xml;base64,bW9kdWxlLmV4cG9ydHMgPSAiZGF0YTppbWFnZS9zdmcreG1sO…
```

**Comment by Phmager** [comment]
I've got the same problem with *.md files when using it directly.

import * as CHANGELOG from 'raw-loader!./../../assets/CHANGELOG.txt';
is correct

import CHANGELOG from 'raw-loader!./../../assets/CHANGELOG.txt';
-> undefined

import * as CHANGELOG from 'raw-loader!./../../assets/CHANGELOG.md';
-> modules.exports = "..."

import CHANGELOG from 'raw-loader!./../../assets/CHANGELOG.md';
-> undefined

**Comment by bebraw** [comment]
Could you provide a small standalone repository to study?

**Comment by FezVrasta** [comment]
I have the same problem, I do:

```
import defaultSpinner from 'raw-loader!./spinner.svg';
```
But I get:
```
module.exports = "data:text/plain;base64,........"
```

I tried @Phmager suggestion without luck.

**Comment by ImranAhmed** [comment]
I'm also seeing some odd behaviour. Trying to load a .md file and seeing this.

module.exports = ""


`const status = require('raw-loader!../../../content/home/status.md');`

```
exports.markdownLoader = {
    test: /\.md$/,
    loader: 'raw-loader'
}
```

**Comment by Zzzen** [comment]
Did you use url-loader for svg resources? @cescoferraro
