### ISSUE TITLE
Is it possible to use raw-loader to get the source for a .vue component that is also bundled in my vuejs application?

### ISSUE THREAD

**Issue by tonylampada** [webpack-contrib/raw-loader#19]
Hi, sorry if this is the wrong place for this. 

I'm trying to use raw-loader to maybe get a solution to [this problem on stackoverflow](http://stackoverflow.com/questions/42334892/show-source-of-vue-component-in-app)

But I'm probably over my head regarding knowledge about webpack and loaders for this.

Should this be possible?

**Comment by tonylampada** [comment]
As a metter of fact, it IS possible, and raw-loader DOES help.
I ended up answering my own question.
Thanks :-)

**Comment by irshadshalu** [comment]
Hey @tonylampada , I know this is quite old and you probably have no idea what was going on, but just a suggestion that next time you solve something that you posted online, please do post the solution as well 😄 
 
As it will help those in future who comes to your thread through searching.
