### ISSUE TITLE
Question: How to import raw files with resolved imports

### ISSUE THREAD

**Issue by lricoy** [webpack-contrib/raw-loader#20]
Hi, I would like to import a file as a string but only **after** webpack has resolved the `import`statements inside of it.

Is that possible?

Basically:

```javascript
// file bar
export const foo = 'I am a string'
```

```javascript
// File 1
import {foo} from './bar'
// more stuff
```

```javascript
import fileAsString from 'raw-loader!./file1'
// resolved {foo} + more stuff
```

**Comment by michael-ciniawsky** [comment]
@lricoy I'm not 💯 if understand what you are trying to do, but a dynamic import maybe? =>

```js
import foo from './foo'

import(./after).then((file) => {
    const resolved = foo + file
    return resolved
})
```

**Comment by Kovensky** [comment]
Webpack does the module resolution _after_ processing through all the loaders, so it's not possible to get the raw output, at least... not with a loader.

This is an implementation detail, but it is possible to access the core webpack runtime function via `__webpack_require__`. Attached to it is an `m` object that holds the function bodies of all modules whose code are currently loaded. This can be combined with the knowledge that `require.resolve`, in webpack, returns the bundled module ID for a given module to get:

```js
__webpack_require__.m[require.resolve('module-name')].toString()
```

**Comment by lricoy** [comment]
I will give it a try. Thanks! 👍

**Comment by michael-ciniawsky** [comment]
@lricoy If there isn't a loader for that propose avaiable already, make one 😛

**Comment by michael-ciniawsky** [comment]
See style-loader for architectual proposes since it does the same for CSS && `<style></style>`

**Comment by lricoy** [comment]
Sounds @michael-ciniawsky I will give it a try this weekend :) You can close this issue if you think is appropriate since it is not raw-loader related anymore. 😄

**Comment by michael-ciniawsky** [comment]
Share a link here If you need any help or have an awesome loader for webpack-contrib :D

**Comment by samouss** [comment]
Hi @lricoy,

Did you manage to inject your script with all the resolved dependencies? I have try the hacky solution mentioned above, but the call of the function only returns the scope of the required module. You still don't have all the dependencies inline inside the module, you just have the reference to it like this:

```js
function (module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_react_dom__ = __webpack_require__(320);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_react_dom___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_react_dom__);

// Some code here

/***/ }
```

**Comment by lricoy** [comment]
Hi @samouss. I have not. I ended up doing a custom plugin that would run after the `build` step and create the files I needed after webpack has bundled them.

**Comment by samouss** [comment]
Ok thanks for the feedbacks 👍 Finally, I am using the MultiCompiler option from Wepback with the RawLoader and it seems to work.
