### ISSUE TITLE
Raw loader adds an extra module.exports = in the bundle.

### ISSUE THREAD

**Issue by richardspence** [webpack-contrib/raw-loader#21]
Using webpack 2.2.1 & raw-loader 0.5.1

The raw-loader will append extra module.exports into the template that is included into the bundle.

Here's an example bundled snippet:
```
/***/ "../node_modules/raw-loader/index.js!./components/template.html":
/***/ (function(module, exports) {

module.exports = "module.exports = \"<div>\\r\\n    I'm a template\\r\\n    </div>\""

/***/ }),
```
.template.html :
```
<div>
    I'm a template
</div>
```
Note the extra module.exports = in the template text

**Comment by richardspence** [comment]
Ahh figured it out.  I had added this in the webpack.conf trying to get it to work, and this causes the duplicate module.exports:

```
   module: {
        rules: [
            {
                test: /\.html?$/,
                use: 'raw-loader'
            }
        ]
    },
```
so I removed that section.

**Comment by michael-ciniawsky** [comment]
@richardspence ? Either `import template from 'raw-loader!./file.html` or add `raw-loader` to `webpack.config.js` and `import template from `./template.html` should work . But **not** both :stuck_out_tongue:
