### ISSUE TITLE
Does not work with a dynamic path

### ISSUE THREAD

**Issue by stephan-v** [webpack-contrib/raw-loader#29]
Whenever I try to use this with a dynamic require path it fails. Is this normal are can this be circumvented somehow?

For example these will fail:

```
var name = 'arrow.svg';
require('!!raw-loader!public/images/svg/ + name');
```

```
var name = 'arrow.svg';
require(`!!raw-loader!public/images/svg/${name}`);
```

While this works fine:

```
require('!!raw-loader!public/images/svg/arrow.svg');
```

The error I get is:

>  ERROR  Failed to compile with 1 errors                                                                                                                                                                    2:45:45 PM
> 
> This dependency was not found:
> 
> * !!raw-loader!public/images/svg/ in ./~/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]]}!./~/vue-loader/lib/selector.js?type
> =script&index=0!./resources/assets/js/components/svg/SvgInline.vue
> 
> To install it, you can run: npm install --save !!raw-loader!public/images/svg/

**Comment by kedrzu** [comment]
Webpack resolves dependencies at build time, so you simply cannot do it at runtime.
