### ISSUE TITLE
Weird behaviour of loader on Docker

### ISSUE THREAD

**Issue by saurabh2590** [webpack-contrib/raw-loader#30]
Hi 
I am using `raw-loader` to load raw xml files in my react project with the following config in my rules for loader.
```
   { 
        test: /\.xml$/,
        exclude: /node_modules|src/,
        loader: 'raw-loader'
      }
```
And build my output with `webpack --config webpack.build.config`. The weird problem is that on my local machine or any machine loader works correctly and emits out xml files as string in the compiled JS.
However, when running inside the docker environment it always complain, 
```
ERROR in ../test/gizmos/FractionPie.xml
Module parse failed: /src/test/gizmos/FractionPie.xml Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| <semantics>
|   <mrow>
|     <mn>2590</mn>
```
I also tried putting console log in the module code itself to check if it is being registered loader and being invoked or not. On local machine, I see all console logs along with content. On Docker it is not even being recognized as the loader and none of the console.log messages appear.

**Comment by d3viant0ne** [comment]
I'm going to need a bit more information on the docker side of things.

1.) Your docker file
2.) Host OS
3.) Docker Version ( i.e. `Version 17.06.0-ce-mac17 (18432)` )

**Comment by d3viant0ne** [comment]
Resolving as no feedback was given. Feel free to re-open should you want to provide the information needed to properly triage this issue
