### ISSUE TITLE
`import * as files from '!raw-loader!./foo';` issue

### ISSUE THREAD

**Issue by alanbsmith** [webpack-contrib/raw-loader#31]
I’m not sure if this is the best place for this question, so I'm happy to remove the issue if so.

With normal JS files I can import them like this:`import * as foo from ‘../some/dir';` and then call it later `foo[‘bar’]`. I’d like to be able to do the same thing, but with the inline raw loader. Something like: `import * as files from ‘!raw-loader!../some/dir’;` and then call the raw file later: `files[‘some-file]`. But that doesn’t work. It parses the raw file into a JSON object with each letter as a key.
Is there a good way to do that?

**Comment by michael-ciniawsky** [comment]
The `raw-loader`'s propose is mainly to convert a raw source into a JS Module with a 'default' export per file) (`export default ${raw}`  || `module.exports = ${raw}`). webpack loaders in general work on a per file basis, you can't require/import a whole directory without adding extra logic :).

**Comment by alanbsmith** [comment]
Thanks for the clarification and the quick response!
