### ISSUE TITLE
Using Raw-loader along with polymer-webpack-loader does not create valid html

### ISSUE THREAD

**Issue by mvinayakam** [webpack-contrib/raw-loader#33]
Hello

I am using polymer webcomponents along with angular4. Including the polymer-webpack-loader messes up the output. Its no longer valid html
<img width="714" alt="screen shot 2017-09-18 at 8 29 36 pm" src="https://user-images.githubusercontent.com/3602564/30548569-298560f6-9cb0-11e7-9464-f1eb19dc2276.png">

Without polymer-webpack-loader, here is the sample of the html file - <img width="857" alt="screen shot 2017-09-18 at 8 30 51 pm" src="https://user-images.githubusercontent.com/3602564/30548634-4f2054ec-9cb0-11e7-80b9-670b81469813.png">

**Comment by mvinayakam** [comment]
The cd in the second snapshot is irritating but the page atleast works as expected.

**Comment by michael-ciniawsky** [comment]
Please provide your config (`webpack.config.js`) aswell, why do you need the `raw-loader` ?

**Comment by mvinayakam** [comment]
I believe raw-loader was part of the reference config we saw. Hence continued using it. I recently tried changing to babel-loader but that wouldn't work either.

Here is the config file zipped to bypass the security check
[webpack.config.js.zip](https://github.com/webpack-contrib/raw-loader/files/1343421/webpack.config.js.zip)

**Comment by michael-ciniawsky** [comment]
It should be possible to use just `polymer-webpack-loader` without the need for `raw-loader`. As this loader literally just adds `export default ${content}` I'm afraid the issue lies somewhere else in your case, so please open an issue @polymer-webpack-loader instead if you still have regressions
