### ISSUE TITLE
raw-loader@1.0.0-beta.0 released on npm as latest?

### ISSUE THREAD

**Issue by oliviertassinari** [webpack-contrib/raw-loader#37]
I believe this new beta should have been released with the `next` tag on npm, not the `latest` one.

**Comment by nelsonomuto** [comment]
This version returns an object and not a string.

**Comment by d3viant0ne** [comment]
That's a mistake, shouldn't have been on the latest dist tag yet. raw-loader is now set to `'dist-tags': { latest: '0.5.1', beta: '1.0.0-beta.0' }`
