### ISSUE TITLE
New version doesn't work properly

### ISSUE THREAD

**Issue by ihntv** [webpack-contrib/raw-loader#38]
New version doesn't work properly with Webpack and Angular

> "compiler.es5.js:1694 Uncaught Error: The template specified for component AppComponent is not a string"...

Webpack: 3.6.0
Angular: 4.4.4

But in your previous version "0.5.1" all works fine

**Comment by ghetolay** [comment]
I've not followed new webpack versions and their requirement but I think it's like for `css-loader` it's returning a js module. Except here we can't use `to-string-loader` as the object returned has no `toString()` function.
Maybe we need a `angular-resource-loader` to handles those cases of module export.

**Comment by d3viant0ne** [comment]
@ihntv - Shouldn't have been on the latest dist tag yet. raw-loader is now set to `'dist-tags': { latest: '0.5.1', beta: '1.0.0-beta.0' }`

**Comment by AnimaMundi** [comment]
@latest is still installing 1.0.0-beta.0

**Comment by d3viant0ne** [comment]
![screen shot 2017-10-03 at 6 30 26 am](https://user-images.githubusercontent.com/8420490/31123168-6125aab6-a804-11e7-9416-5ba4397b3ce2.png)

**Comment by AnimaMundi** [comment]
No lockfile, but I tried it again and now it's working 😆 Maybe it was cached locally by NPM.
