### ISSUE TITLE
raw-loader does not working with Jasmine test for Angular 5

### ISSUE THREAD

**Issue by Bmahecha123** [webpack-contrib/raw-loader#47]
When I attempt to write a simple integration test for Angular 5 I get the following error when trying to configure my TestBed:
```Error: Cannot find module 'raw-loader!./demo-text.md' from 'MyComponent'```

Has anyone else experienced this testing Angular 5 applications which make use of raw-loader? Thanks for your time.

**Comment by evilebottnawi** [comment]
@Bmahecha123 `'raw-loader!./demo-text.md' from 'MyComponent'` => `'raw-loader!./demo-text.md' (without from)
