### ISSUE TITLE
with html-loader, the  html-loader parse fail 

### ISSUE THREAD

**Issue by luampm** [webpack-contrib/raw-loader#48]
where used with html-loader, the html complier   fail. 

ERROR in   Error: Parse Error: <html lang=\"en\">\r\n\r\n<head>\r\n  <meta chars
et=\"UTF-  8\">\r\n\r\n  <title>slider</title>\r\n  <meta name=\"viewport\"\r\n
       co  ntent=\"width=device-width, initial-scale=1.0, user-scalable=no, mini
mum-scale  =1.0, maximum-scale=1.0\">\r\n</head>\r\n\r\n<body>\r\n<ul>\r\n\r\n</
ul>\r\n\r  \n<script type="text/javascript" src=".././js/vendors.js?271daa494a16
c3d5e559"  ></script><script type="text/javascript" src=".././js/slider.js?271da
a494a16c3  d5e559"></script></body>\r\n\r\n</html>"

  - htmlparser.js:235 new HTMLParser
    [Component]/[html-minifier]/src/htmlparser.js:235:13

  - htmlminifier.js:944 minify
    [Component]/[html-minifier]/src/htmlminifier.js:944:3

  - htmlminifier.js:1304 exports.minify
    [Component]/[html-minifier]/src/htmlminifier.js:1304:10

  - index.js:309 Promise.resolve.then.then.html
    [Component]/[html-webpack-plugin]/index.js:309:18

  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7

here is my config: 
 "css-loader": "^0.28.10",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.0.6",
    "raw-loader": "^0.5.1",
    "style-loader": "^0.20.2",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.10",
    "webpack-dev-server": "^3.1.0"

after i remove the raw-loader,   it is fine !

**Comment by michael-ciniawsky** [comment]
> after i remove the raw-loader, it is fine !

You wont need the `raw-loader` when using the `html-loader` already, it's either not both :)
