### ISSUE TITLE
Export incompatibility with raw-loader and awesome-typescript-loader

### ISSUE THREAD

**Issue by ProdigySim** [webpack-contrib/raw-loader#54]
* Operating System: MacOSX
* Node Version: 8
* NPM Version: yarn 1.7.0
* webpack Version: 4.12.0
* webpack-serve Version: none

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
I have some code to import an SVG in Typescript. Here are some relevant snippets:

Importing an SVG in a typescript file:
```ts
import addLgSvg from './add-lg.svg';

const icons = {
   'add-lg': addLgSvg,
};
export default icons;
```

And of course I have defined this silly typescript module declaration to help:
```ts
declare module "*.svg" {
  const content: string;
  export default content;
}
```

##### webpack.config.js

```js
// module.rules = [ ...
            { test: /\.tsx?$/, loader: "awesome-typescript-loader" },
            {
                test: /\.(svg)$/,
                use: [
                    {
                        loader: 'raw-loader',
                    },
                ],
            },
// ... ];
```

### Expected Behavior

SVG should be imported and exported as expected.

### Actual Behavior
Somehow there is incompatibility between the `raw-loader` export and the typescript import.

`raw-loader` compiles my SVG as:
```js
"./icons/add-lg.svg": /*!**************************!*\
  !*** ./icons/add-lg.svg ***!
  \**************************/
    /*! no static exports found */
    /***/
    (function(module, exports) {

        module.exports = "<svg > ... </svg>\n"

        /***/
    }
    ),
```

`awesome-typescript-loader` generates this output however: 
```js
    (function(module, exports, __webpack_require__) {

        "use strict";

        Object.defineProperty(exports, "__esModule", {
            value: true
        });

        var add_lg_svg_1 = __webpack_require__(/*! ./add-lg.svg */
            "./icons/add-lg.svg");
        var icons = {
            'add-lg': add_lg_svg_1.default,
        };
        exports.default = icons;
});
````

In the above snippet, `var add_lg_svg_1` is a string with the SVG content. However, it has been compiled to `add_lg_svg_1.defeault`, which does not exist.

Screenshots:
<img width="295" alt="screen shot 2018-06-19 at 4 59 56 pm" src="https://user-images.githubusercontent.com/857937/41626788-1592f95e-73e3-11e8-8574-e7172e435faf.png">

<img width="255" alt="screen shot 2018-06-19 at 5 00 06 pm" src="https://user-images.githubusercontent.com/857937/41626838-4d02b028-73e3-11e8-82bc-53201e5d29b5.png">

### How Do We Reproduce?

I can try to produce a limited test case if necessary.

I'm not sure how to resolve this, and whether the culprit is this project or the typescript-loader, or my usage.

**Comment by ProdigySim** [comment]
I managed to get this working by changing my typescript module declaration to:

```ts
declare module "*.svg" {
  const content: string;
  export = content;
}
```

and using 

```ts
import * as addLgSvg from './add-lg.svg';
```

for my import statement.

Still, it would be nice if we could get a default export.

**Comment by evilebottnawi** [comment]
@ProdigySim problem still exists?

**Comment by ProdigySim** [comment]
It seems to be working now; I'm not sure why it was failing 🤷‍♂️ .

Welp!
