### ISSUE TITLE
The variable contains the path to the file instead of the text

### ISSUE THREAD

**Issue by khusamov** [webpack-contrib/raw-loader#55]
The cities variable contains the path to the file instead of the text:

```
module.exports = __webpack_public_path__ + "static/media/cities.b4c5b41d.txt";
```

My code:

```javascript
import cities from './cities.txt';
```

Config:

```javascript
    rules: [
		{
			test: /\.txt$/,
			use: 'raw-loader'
		}
    //....
     ]
```

**Comment by evilebottnawi** [comment]
@khusamov you have invalid configuration, `file-loader` already handle you import, please provide config

**Comment by evilebottnawi** [comment]
Feel free to feedback :+1:

**Comment by khusamov** [comment]
What is `file-loader`?  
How do I import the contents of text files correctly?

**Comment by amoshydra** [comment]
If this is a one-time import you can override your default webpack loader config by prepending an `!` in front. 

Check this out https://github.com/webpack/webpack/issues/1747#issuecomment-164561113

```js
var template = require('!raw-loader!mytemplate.html');
```
