### ISSUE TITLE
Cannot import file using typescript

### ISSUE THREAD

**Issue by danman113** [webpack-contrib/raw-loader#56]
* Operating System: OSX
* Node Version: v8.11.3
* NPM Version: 5.6.0
* webpack Version: ^4.19.1
* raw-loader Version: ^0.5.1

This issue is for a:

- [x] **bug**
- [ ] **feature** request
- [ ] **modification** request

### Code
```
import txt from './simple.txt'
```
##### CLI Command

```bash
  webpack
```

##### webpack.config.js

[webpack.config.js](https://gist.github.com/danman113/33c508375d37bc4319cf63b9c5318dbf)

##### tsconfig

```
{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5"
  },
  "include": [
    "./src/**/*"
  ]
}
```

### Expected Behavior

Should load the file and return a string to `txt`

### Actual Behavior

Get the following error after running webpack

```
ERROR in [at-loader] ./src/index.ts:3:17
    TS2307: Cannot find module './simple.txt'.
```

### How Do We Reproduce?

Simply use the webpack config and import. package.json can be provided as well.

Not really sure if this is an error with the loader, webpack, my config, or `awesome-typescript-loader`

Also before you asked, I also tried `import txt from 'raw-loader!./simple.txt'` and `import txt from './simple.txt'`, no dice.

Thanks!

**Comment by evilebottnawi** [comment]
@danman113 it is not bug webpack, looks you should ignore some files in `tsconfig`

**Comment by danman113** [comment]
@evilebottnawi That doesn't seem to work. I updated my .tsconfig to the following without any luck:
```{
  "compilerOptions": {
    "outDir": "./dist/",
    "sourceMap": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5"
  },
  "include": [
    "./src/**/*.ts"
  ],
  "exclude": [
    "./src/**/*.txt"
  ]
}```

Still get
```
ERROR in [at-loader] ./src/index.ts:3:22
    TS2307: Cannot find module './simple.txt'.
```

**Comment by danman113** [comment]
Okay so I figured out what the problem was, it's definitely not a problem with webpack or the loader, but how typescript handles modules.

The fix was simply to add a `[filename].d.ts` file in the same directory as  with a declaration `declare module '*.[filename]'` in it. Adding these declaration files is what should fix all of these bugs.

**Comment by satorioh** [comment]
By the way, if  use `import ...  from` syntax in your ts file may get silent failure, using `import * as ... from` will work well

**Comment by jasonqsong** [comment]
For whoever runs into the same question (like me) in the future. The answer is in the [official typescript doc][doc]. You'll need to tell typescript that your module will be a string type (or other type).

In raw loader case, the files would look like this:
> textfile.txt
```text
some text
```

> textfile.txt.d.ts, the type definition of textfile, next to textfile.txt
```typescript
declare module "raw-loader!*" {
    const content: string;
    export default content;
}
```

> code.ts
```typescript
import consttext from "raw-loader!./textfile.txt"
```
Now typescript would be happy about the string type variable "consttext".

[doc]: https://www.typescriptlang.org/docs/handbook/modules.html#wildcard-module-declarations
