### ISSUE TITLE
Imported string contains module.exports

### ISSUE THREAD

**Issue by WouterFlorijn** [webpack-contrib/raw-loader#62]
* Operating System: Windows
* Node Version: 8.9.1
* NPM Version: 6.7.0
* webpack Version: 4.29.0
* raw-loader Version: 1.0.0

### Expected Behavior

Raw document contents are imported as string.

### Actual Behavior

Imported string is

```
'module.exports = "file contents"'
```

### Code

```js
  // webpack.config.js
  ...
  module: {
    rules: [
      {
        test: /\.txt$/,
        use: 'raw-loader'
      }
    ]
  }
  ...
```

Also tried `'raw-loader!file-name.md'`.

### How Do We Reproduce?

I'm using Nuxt (might be relevant somehow). I just want to load an md file to a string and then render it.

**Comment by evilebottnawi** [comment]
@WouterFlorijn Can you create minimum reproducible test repo?

**Comment by evilebottnawi** [comment]
Code is simple https://github.com/webpack-contrib/raw-loader/blob/master/index.js and i think problem in confguration

**Comment by evilebottnawi** [comment]
@WouterFlorijn 'raw-loader!file-name.md' should work in server side, it think problem in configurationm can you provide minimum reproducible test repo?
