### ISSUE TITLE
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = "{\...'

### ISSUE THREAD

**Issue by jgcmarins** [webpack-contrib/raw-loader#64]
* Operating System:
macOS Mojave: 10.14
* Node Version:
v10.15.1
* NPM Version:
6.4.1
* webpack Version:
4.29.3
* raw-loader Version:
1.0.0

### Expected Behavior

To load load this json file:

```json
{
  "expo": {
    "name": "My Awesome Project",
    "slug": "my-awesome-project",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "platforms": [
      "ios",
      "android"
    ],
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true
    }
  }
}
```

### Actual Behavior

```
Module parse failed: Unexpected token m in JSON at position 0 while parsing near 'module.exports = "{\...'
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = "{\...'
    at JSON.parse (<anonymous>)
```

### Code

```mdx
<div style={{fontSize: 28}}>
<CodeSurfer
  title="Development Path - Splash Screen"
  code={require('!raw-loader!../my-awesome-project/app.json')}
  showNumbers={false}
  dark={true}
  lang="json"
  steps={[
    { range: [15, 15], notes: 'To setup a splash screen, just add a file named splash.png to assets folder'},
  ]}
/>
```

### How Do We Reproduce?

check this repo: https://github.com/jgcmarins/react-native-cryptocurrency

**Comment by evilebottnawi** [comment]
Use `raw-loader!../my-awesome-project/app.json` (exclude first `!`)

**Comment by jgcmarins** [comment]
Thanks

**Comment by swapnildalvi2002** [comment]
Any solution on this I am also facing same issue 
when use raw-loader!
var enUs = require( 'raw-loader!../../data/translations/en-US.json' );
ERROR:
\SyntaxError: Unexpected token e in JSON at position 0 while parsing near 'export default "{\n

And when use json-loader!
var enUs = require( 'json-loader!../../data/translations/en-US.json' );
ERROR
SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"m

**Comment by RezaZR** [comment]
> Any solution on this I am also facing same issue
> when use raw-loader!
> var enUs = require( 'raw-loader!../../data/translations/en-US.json' );
> ERROR:
> \SyntaxError: Unexpected token e in JSON at position 0 while parsing near 'export default "{\n
> 
> And when use json-loader!
> var enUs = require( 'json-loader!../../data/translations/en-US.json' );
> ERROR
> SyntaxError: Unexpected token m in JSON at position 0 while parsing near 'module.exports = {"m

I'm having the same issue here. Any progress?

**Comment by followgiant** [comment]
```
{
    test: /\.json$/,
    use: ['json-loader'],
    type: 'javascript/auto'
}
```
This works for me!
