### ISSUE TITLE
Not working with require statements

### ISSUE THREAD

**Issue by ir-fuel** [webpack-contrib/raw-loader#72]
* Operating System:
macOS Mojave

* Node Version:
8.9.1

* NPM Version:
6.5.0

* webpack Version:
4.29.6

* raw-loader Version:
2.0.0

### Expected Behavior

`import` and `require` should both inline the file contents

### Actual Behavior

`import`works, but `require` doesn't.

### Code

example:

```
import Test from '../../../shader/pbr.glslv'
const Test2 = require('../../../shader/pbr.glslv')
```

when logging both in the console, for `Test` I get the contents of the file, but for `Test2` I get 
```
Module {default: "//camera.matrixWorld
↵uniform mat4 viewMatrixInver…tion = projectionMatrix * positionInViewSpace;
↵}", __esModule: true, Symbol(Symbol.toStringTag): "Module"}
```

I used to run webpack 3.8.1 and raw-loader 0.5.1 before and there everything worked. It stopped working after upgrading everything to the latest version.

```
module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            plugins: [
              "transform-decorators-legacy",
              "react-hot-loader/babel"
            ],
            presets: [
              "env", "react", "stage-1"
            ]
          }
        }
      },
      {
        test: /\.(glslf|glslv)$/,
        use: 'raw-loader'
      },
      {
        test: /\.css$/,
        exclude: /node_modules/,
        use: ["style-loader", "postcss-loader"]
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
          'file-loader?hash=sha512&digest=hex&name=[hash].[ext]',
          'image-webpack-loader'
        ]
      }
    ]
  },
```

### How Do We Reproduce?

Use `import` and `require` on the same file and `console.log` the result

**Comment by ir-fuel** [comment]
Downgrading to 1.0.0 solves the issue

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/raw-loader/releases/tag/v2.0.0

Use `default`

**Comment by ir-fuel** [comment]
What do you mean by "use Default" ?

**Comment by evilebottnawi** [comment]
@ir-fuel `require('something').default` or rewrite your code base on `import`, it is first releases for better supporting `import`, without this breaking change we never migrate on `ES` modules

**Comment by ir-fuel** [comment]
Adding `.default` has indeed solved it.
I'm filling an object with a bunch of external file contents.

```
const vertexShaders = {
  pbr: require('../../../shader/pbr.glslv').default,
  outline: require('../../../shader/outline.glslv').default,
  outline_mask: require('../../../shader/outline_mask.glslv').default,
  background: require('../../../shader/background.glslv').default
}
```
This is afaik not something that can be done using `import` statements

**Comment by evilebottnawi** [comment]
@ir-fuel all can be done using `import`, just move all `require` on top and change this to `import`, because it is doesn't has sense in you example

**Comment by ir-fuel** [comment]
Sure it is technically possible. It's just more code to write as I have to import everything first and then insert it in the object.

**Comment by evilebottnawi** [comment]
@ir-fuel anyway if you have idea how we can handle `ES` and `require` PR welcome

**Comment by evilebottnawi** [comment]
Maybe `exports.default = module.exports = value`, need add test for this to check tree shaking

**Comment by evilebottnawi** [comment]
`exports.default = module.exports` break tree shaking, so better use `.default` for `require`

**Comment by VitaliyR** [comment]
It's better to update the README about this functionality :)

**Comment by runfaj** [comment]
> It's better to update the README about this functionality :)

This is an es6 transpiling thing via babel - it doesn't really have to do with raw-loader. It is documented in babel's documentation. If people are having the issue though, finding this issue (like I did) via a search engine works well enough.
