### ISSUE TITLE
error when using with SCSS and angular7

### ISSUE THREAD

**Issue by daB0bby** [webpack-contrib/raw-loader#76]
* Operating System: macOS 10.14.4
* Node Version: v11.14.0
* NPM Version: 6.9.0
* webpack Version: 4.30.0
* raw-loader Version: 2.0.0

### Expected Behavior

Wokring like it does with `1.0.0`

### Actual Behavior

After upgrading `raw-loader` to `2.0.0` I always receive this error from Angular:
```
Uncaught Error: Expected 'styles' to be an array of strings.
```

Using Angular `7.2.14`.

### Code

This is my configuration for my SCSS and CSS:

```js
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        loaders: ['raw-loader', 'sass-loader']
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              hmr: process.env.NODE_ENV === 'development',
            },
          },
          'css-loader',
        ]
      }
```

This setup works fine with `raw-loader` `1.0.0`.

**Comment by evilebottnawi** [comment]
You need rewrite you code, please see note about breaking change, now it is harmony module, please provide you minimum reproducible test repo and i will show how do this in right way, thanks

**Comment by rbirkgit** [comment]
I have the same issue. Took my Ang7 code and added "raw-loader" 2.,0 and I get the styles error starting up my app. No other changes. Changed to 1.0 and my app starts up. I don't understand what I need to do in order to use v2.0? Or is it not compatible with default Ang7 CLI apps?

**Comment by evilebottnawi** [comment]
@rbirkgit rewrite from require to import

**Comment by cheng93** [comment]
FWIW I tried that and the error still occurs, i.e

```ts
import scss from "./file.scss";

@Component({
  ...
  styles: [scss],
  ...
})
```

```js
{
    exclude: [
        path.resolve(__dirname, "./app/app.scss"),
        path.resolve(__dirname, "./app/kendo.scss")
    ],
    test: /\.scss$/,
    use: [{ loader: "raw-loader" }, { loader: "sass-loader" }],
    exclude: ExclusionRegexs
}
```

**Comment by evilebottnawi** [comment]
@cheng93 please create new issue with **minimum** reproducible test repo

**Comment by rbirkgit** [comment]
Maybe I am not explaining. All I did was adding "raw-loader" to my packages.json and ran yarn install. No code changes at all. Then I can no longer start my app with the styles errors. Going back to v1 it works again. I have not got as far as trying to import.
