### ISSUE TITLE
The template specified for component AppComponent is not a string

### ISSUE THREAD

**Issue by subramn** [webpack-contrib/raw-loader#78]
When i try to upgrade an existing angular app using webpack , raw-loader, to 2.0.0 started receiving  this error.
webpack build was successful, but when i ran the app in browser got this error.

when i downgraded to earlier version of raw-loader its working fine.

**Comment by Klaster1** [comment]
@subramn are you using angular2-template-loader? Is true, there's a similar issue still opened https://github.com/TheLarkInn/angular2-template-loader/issues/86.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/raw-loader/issues/77

**Comment by evilebottnawi** [comment]
Investigate

**Comment by evilebottnawi** [comment]
@subramn #77 
@Klaster1 problem in `angular2-template-loader` 
probably angular2-template-loader should upgrade to generate `import`s too.
that would make it compatible with raw-loader 1 and 2
so feel free to send a PR with fix to this repo
