### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by sundylink** [webpack-contrib/raw-loader#87]
require('!!raw-loader!./test.md')
error:
Unexpected token
You may need an appropriate loader to handle this file type.
| export default "# test"

**Comment by sundylink** [comment]
webpack 1.x 

node 6.9.0
raw-loader 2.0.0

**Comment by evilebottnawi** [comment]
Update webpack version, webpack@1 is deprecated

**Comment by sundylink** [comment]
@evilebottnawi  There is no deprecation, the solution is to reduce the raw-loader version, what is the reason？
