### ISSUE TITLE
Can raw-loader catch all

### ISSUE THREAD

**Issue by elgs** [webpack-contrib/raw-loader#92]
The example in the README.md suggests .txt$ has to be configured in order for this loader to load .txt file. I wonder if this loader could be configured as a catch all loader, meaning it could catches everything not caught be other loaders?

**Comment by evilebottnawi** [comment]
Yes, just use:
```
{
  loader: require.resolve('raw-loader'),
  // Just add all regexp from other `test` loaders
  exclude: [
    // babel-loader
    /\.(js|mjs|jsx|ts|tsx)$/, 
    // webpack built-in module
    /\.json$/,
    // css-loader
    /\.css$/
    // etc
],
}
```

**Comment by elgs** [comment]
Thank you so much. It worked! I think this should be the primary use of this loader.

**Comment by evilebottnawi** [comment]
@elgs We have an issue for this in webpack, maybe for webpack@5 we will implement an option to enable this behavior without extra setup
