### ISSUE TITLE
`Module not found` when using TypeScript project references

### ISSUE THREAD

**Issue by trbabb** [webpack-contrib/raw-loader#95]
- Operating System: OSX Catalina
- Node Version: 12.10.0
- NPM Version: 6.14.5
- webpack Version: 4.43.0
- raw-loader Version: 4.0.1

### Expected Behavior

When using `raw-loader` with TypeScript references— For any given module `X.ts`, I'd expect import paths relative to `X.ts` to refer to the same resources whether `X` is imported from within its own project, or from a module in a different project.

Clone https://github.com/trbabb/rawloader-repro.git, and after `npm install`, run `npx webpack`. I'd expect `src/Foo.ts` to find `./shad/foo.frg` and import it normally. 

### Actual Behavior

`npx webpack` in the above repo yields:

    ERROR in /project/path/src/Foo.ts
    ./src/Foo.ts
    [tsl] ERROR in /project/path/src/Foo.ts(1,19)
          TS2307: Cannot find module './shad/foo.frg' or its corresponding type declarations.

This is not the case if `src/Foo.ts` is compiled from within its own project. This can be seen if you:

    > mv webpack.config.js webpack.config.js-broken
    > mv webpack.config.js-working webpack.config.js
    > npx webpack

This compiles normally, and the contents of `foo.frg` can be found inside the bundle as expected.

Somehow, the existence of project reference breaks the relative path in `src/Foo.ts`. 

### Code / How to reproduce

    git clone https://github.com/trbabb/rawloader-repro.git
    npm install
    npx run webpack

Please let me know if there's anything I need to configure differently to get this to work. Thanks!

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/raw-loader/issues/54#issuecomment-398570019

**Comment by evilebottnawi** [comment]
Sorry, not related to `raw-loader`, looks like `ts-loader` doesn't respect loading declarations from relative import, please one a new issue, as workaround you can put declarations on top of project, I can't help here

**Comment by trbabb** [comment]
Filed https://github.com/TypeStrong/ts-loader/issues/1127 .
