### ISSUE TITLE
Module Not Found

### ISSUE THREAD

**Issue by stoplion** [webpack-contrib/raw-loader#96]
- Operating System: 10.14.6
- Node Version: v10.20.1
- NPM Version: 6.14.4
- webpack Version: 4.4
- raw-loader Version: 4.0.1

### Expected Behavior

Adding raw loader to import markdown files:
```
  test: /\.md$/i,
      use: [{
        loader: 'raw-loader',
        options: {
          esModule: false
        }
      }],
```

In `.js` file, require the markdown file..
```
return require(postPath)
// postPath is '../posts/awards.md'
```

```
Error: Cannot find module '../posts/awards.md'
at webpackEmptyContext (eval at <path to file>)
....
```

the path to markdown file is the relative path: `/posts/awards.md`

**Comment by evilebottnawi** [comment]
Please do not remove `How Do We Reproduce?`, I can't help without it, also problem not related to `raw-loader`, looks you have wrong path or file doesn't exist
